`ifndef FRAMEWORK_PARAMS_SVH
`define FRAMEWORK_PARAMS_SVH

`define AXI_ADDR_W 32
`define AXI_DATA_W 32
`define AXI_ID_W 4
`define AXI_USER_W 1

`define AXI_FIFO_DEPTH 2
`define AXI_FIFO_FALL_THROUGH 1'b0

`define AXI_F_LGDEPTH 16
`define AXI_F_AXI_MAXSTALL 10000
`define AXI_F_AXI_MAXRSTALL 10000
`define AXI_F_AXI_MAXDELAY 10000

`endif
